package com.iwr.pdv.audit.domain;

public enum AuditAction {
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    LOGOUT,
    ACCESS_DENIED,
    USER_CREATED,
    USER_UPDATED,
    USER_PASSWORD_CHANGED,
    CASH_REGISTER_OPENED,
    CASH_REGISTER_CLOSED,
    CASH_MOVEMENT_CREATED,
    PRODUCT_CREATED,
    PRODUCT_UPDATED,
    PRODUCT_PRICE_CHANGED,
    PRODUCT_STOCK_CHANGED,
    SALE_CANCELLED,
    PROMISSORY_NOTE_CREATED,
    PROMISSORY_NOTE_PAID,
    PROMISSORY_NOTE_COLLECTION_REGISTERED,
    PROMISSORY_NOTE_RENEGOTIATED
}
