import { lazy, Suspense, useEffect, useState } from 'react'
import type { LucideIcon } from 'lucide-react'
import { BarChart3, ChevronDown, ClipboardList, FileSpreadsheet, Gift, History, Package, PlusCircle, ReceiptText, Search, ShieldCheck, Tags, UserPlus, Users } from 'lucide-react'
import './App.css'
import './final-refinement.css'
import './admin-dashboard-engineered.css'

import { LoginPage } from './pages/LoginPage'
import { getCurrentUser, logout } from './services/authService'
import { clearAuthToken, getAuthToken } from './services/httpClient'
import { useMediaQuery } from './hooks/useMediaQuery'
import type { AuthUser } from './types/auth'

type AppView =
  | 'checkout'
  | 'history'
  | 'admin-dashboard'
  | 'promissory-notes'
  | 'promissory-create'
  | 'promissory-report'
  | 'loyalty'
  | 'customers-create'
  | 'customers-list'
  | 'customer-profile'
  | 'products-create'
  | 'products-list'
  | 'products-labels'
  | 'product-edit'
  | 'audit'
  | 'users'
  | 'customer-birthdays'